baseURL = "https://conproly.com"
languageCode = "en-us"
title = "Conproly"
theme = "labtime"
enableRobotsTXT = true
copyright = "Copyrighted by Jaap de Vos. All rights reserved."

[params]
  subtitle = "read about technology, with a focus on networking and automation, and whatever else comes along"

[blackfriday]
  hrefTargetBlank = true

[author]
  name = "Jaap de Vos"
